# --- Run Management --- #
run_name: auto
result_dir: ./results
checkpoint_dir: ./checkpoints/t2sm
random_seed: 42

# --- Dataset --- #
dataset:
  mean_path   : ./checkpoints/t2m/Comp_v6_KLD005/meta/mean.npy
  std_path    : ./checkpoints/t2m/Comp_v6_KLD005/meta/std.npy
  # mean_path   : ./dataset/smoodi/Mean.npy
  # std_path    : ./dataset/smoodi/Std.npy
  min_frames  : 40
  max_frames  : 196
  unit_length : 4
  split_file  : ./dataset/smoodi/train.txt

  # motion_dir  : ./dataset/100style/new_joint_vecs
  # text_dir    : ./dataset/100style/texts
  style_json  : ./dataset/100style/100style_clean_clean.json
  batch_size  : 32
  # content_json: ./dataset/100style/10content_clean_clean.json
  # min_frames  : 128
  # max_frames  : 128

# --- Sampler Settings --- #
sampler:
  type: MixedSampler
  batch_size: 32
  samples_per_style: 4

# --- Model --- #
model:
  denoiser:
    transformer:
      layer:
        attention:
          lora:
            type: StyleLoRA
            rank: 8
            scale: 1.0
            style_dim: 256
            num_layers: 4
            in_dim: 256
            out_dim: 256
            hidden_dim: 512
            block:
              dropout: 0.1
              style_dim: 256
              hidden_dim: 512
              num_heads: 8
        film: {}
  style_encoder: 
    type: AxialStyleEncoder
    dropout: 0.1
    style_dim: 256
    num_layers: 4
    block:
      dropout: 0.1
      style_dim: 256
      hidden_dim: 512
      num_heads: 8
  text_drop: 0.1
  style_drop: 0.1
  text_weight: 7.5
  style_weight: 5.5
  cond_weight: 1.5

# --- Losses --- #
loss:
  style:
    weight: 1.0
  content:
    weight: 1.0
  cycle:
    weight: 1.0
  supcon:
    weight: 1.0
    temperature: 0.07

# --- Early Stopper --- #
early:
  patience: 10
  min_delta: 0.0
  mode: min

# --- Calibration --- #
steps: 300
tau: 0.001

# --- Training --- #
epochs: 200
lr: 0.0001
valid_size: 0.2